### ISSUE TITLE
bundler-transformer error with array syntax for globals

### ISSUE THREAD

**Issue by vejja** [nuxt/scripts#121] opened 2024-07-01 22:47 UTC
I'm trying to load CF Turnstile with the following configuration :

```ts
export default defineNuxtConfig({
  scripts: {
      globals: [
        [ 
          { 
            src: 'https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit'
          }, 
          {
            use: () => {
              //@ts-expect-error
              return window.turnstile
            }
          }
        ]
      ]
    }
})
```

I'm getting the following error:

![Capture d’écran 2024-07-02 à 00 46 25](https://github.com/nuxt/scripts/assets/7295259/e6d50924-7f9c-49c8-bf7e-c98d7e840f38)

Looks like an extra closing bracket is being inserted at the end of the `useScript` function in the virtual plugin ?

**Comment by vejja** [comment] 2024-07-03 08:20
Probably similar to #115

**Comment by harlan-zw** [comment] 2024-07-03 09:54
Thanks for the report, this is indeed a duplicate of #115.

However, I will note that we can only support serializable data within the nuxt config. So anything using functions isn't supported, I've included type improvements around this.

I'm putting some more thought into the API around the globals so may look a bit different soon.

**Comment by vejja** [comment] 2024-07-03 13:06
Ok understood
Let’s close then?

**Closed** 2024-07-04 07:36 UTC
